import sys
import os
from pathlib import Path
import importlib.util

# Add Backend to sys.path
repo_root = Path(__file__).resolve().parent.parent
backend_path = repo_root / "Backend"
sys.path.insert(0, str(backend_path))

try:
    from sqlalchemy.schema import CreateTable
    from sqlalchemy.dialects import postgresql
    from app.models.base import Base
    
    # Forcefully import every single .py file in app/models to register all tables/associations
    models_dir = backend_path / "app" / "models"
    for root, dirs, files in os.walk(models_dir):
        for file in files:
            if file.endswith(".py") and file != "__init__.py":
                file_path = os.path.join(root, file)
                # Calculate module name
                rel_path = os.path.relpath(file_path, backend_path)
                module_name = rel_path.replace(os.path.sep, ".").replace(".py", "")
                
                spec = importlib.util.spec_from_file_location(module_name, file_path)
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)

    def generate_sql():
        sorted_tables = Base.metadata.sorted_tables
        
        sql_output = []
        sql_output.append("-- Aura v3 Database Schema (PostgreSQL)")
        sql_output.append("-- Generated by AI Seeder Assistant (Absolute Harvest Mode)")
        sql_output.append("-- Excludes AI Assistant tables (if any were in metadata)")
        sql_output.append("\n")

        for table in sorted_tables:
            if "assistant" in table.name.lower():
                continue
                
            ddl = CreateTable(table).compile(dialect=postgresql.dialect())
            sql_output.append(str(ddl).strip() + ";")
            sql_output.append("\n")
            
        return "\n".join(sql_output)

    if __name__ == "__main__":
        sql_content = generate_sql()
        with open(repo_root / "db.sql", "w") as f:
            f.write(sql_content)
        
        # Internal count for confirmation
        table_count = len([t for t in Base.metadata.sorted_tables if "assistant" not in t.name.lower()])
        print(f"Harvest complete. Found {table_count} tables.")
        print(f"Schema updated at {repo_root / 'db.sql'}")

except Exception as e:
    import traceback
    print(f"Error generating SQL: {str(e)}")
    traceback.print_exc()
    sys.exit(1)
